### ISSUE TITLE
Warnings present for require-cfn-role on sls deploy

### ISSUE THREAD

**Issue by matt-d-webb** [SamWSoftware/ServerlessYoutubeSeries#1]
https://github.com/SamWSoftware/ServerlessYoutubeSeries/blob/614c609e40be1f4167cd3eabe2e64ac6f7effafd/serverless.yml#L41

When running this I am getting a warning for the `cfnRole` as shown below:

![image](https://user-images.githubusercontent.com/36933715/90940620-54648800-e407-11ea-8fe4-7b6e913cfc78.png)

I assume this is simple plugin + property needed on the `serverless.yml file`

**Comment by SamWSoftware** [comment]
this is just a parameter you can add to the provider object if you want to
specify an exact role which is to be used as the runner for the
cloudformation.


cfnRole: arn:aws:iam::XXXXXX:role/role # ARN of an IAM role for
CloudFormation service. If specified, CloudFormation uses the role's
credentials

**Comment by matt-d-webb** [comment]
Thank you. I was quickly googling around to get a quick answer to this, which didn't seem that straight forward - unless you understand how roles work, which I clearly do not! :smile:
